---
extends: stylelint-config-standard
rules:
  at-rule-no-unknown:
  - true
  - ignoreAtRules:
    - extend
    - mixin
    - if
    - content
    - include
    - else
    - return
    - function
  declaration-empty-line-before:
  - always
  - except:
    - first-nested
    ignore:
    - after-declaration
